name: 'semantic-version Common Dependencies'
description: 'Common dependencies to use the semantic-version'
runs:
  using: "composite"
  steps:

## /var/cache/apt/archives does not have access right.
#    - name: Cache apt Packages
#      uses: actions/cache@v3
#      env:
#        cache-name: semantic-version
#      with:
#        path: /var/cache/apt/archives
#        key: ${{ runner.os }}-apt-${{ env.cache-name }}
#        restore-keys: ${{ runner.os }}-apt-

    - name: Cache npm Packages
      uses: actions/cache@v3
      env:
        cache-name: semantic-version
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-npm-

    - name: Install Homebrew Dependencies
      run: source ${GITHUB_ACTION_PATH}/brew-dependencies.sh
      shell: bash

    - name: Install npm Dependencies
      run:  source ${GITHUB_ACTION_PATH}/npm-dependencies.sh
      shell: bash